name: RSS TELEGRAM
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
#env:
#  TZ: Asia/Shanghai

jobs:
    search-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21.x
        - name: Checkout code
          uses: actions/checkout@v2
        - name: build
          run: go run main.go --tg_bot=${{secrets.BOT_TOKEN}} --tg_weekly_channel=${{secrets.CHANNEL_WEEKLY_ID}} --tg_blogs_channel=${{secrets.CHANNEL_BLOGS_ID}} --tg_news_channel=${{secrets.CHANNEL_NEWS_ID}}
